spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@oracle.fiap.com.br:1521/ORCL
    username: ${DB_USER}
    password: ${DB_PASS}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  thymeleaf:
    cache: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: rm554983

server:
  error:
    include-message: always
