CREATE TABLE moto (
  id       NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  placa    VARCHAR2(10) NOT NULL,
  modelo   VARCHAR2(60),
  cor      VARCHAR2(30),
  status   VARCHAR2(20) NOT NULL,
  CONSTRAINT uk_moto_placa UNIQUE (placa)
);


CREATE TABLE vaga (
  id       NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo   VARCHAR2(10) NOT NULL,
  setor    VARCHAR2(20),
  status   VARCHAR2(20) NOT NULL,
  CONSTRAINT uk_vaga_codigo UNIQUE (codigo)
);

CREATE INDEX idx_vaga_status ON vaga(status);

CREATE TABLE alocacao (
  id       NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  moto_id  NUMBER(19) NOT NULL,
  vaga_id  NUMBER(19) NOT NULL,
  inicio   TIMESTAMP  NOT NULL,
  fim      TIMESTAMP  NULL,
  ativa    CHAR(1)    DEFAULT 'S' NOT NULL,
  CONSTRAINT ck_aloc_ativa CHECK (ativa IN ('S','N')),
  CONSTRAINT fk_aloc_moto FOREIGN KEY (moto_id) REFERENCES moto(id),
  CONSTRAINT fk_aloc_vaga FOREIGN KEY (vaga_id) REFERENCES vaga(id)
);

CREATE INDEX idx_aloc_moto  ON alocacao(moto_id);
CREATE INDEX idx_aloc_vaga  ON alocacao(vaga_id);
CREATE INDEX idx_aloc_ativa ON alocacao(ativa);

CREATE TABLE usuario (
  id       NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR2(50)  NOT NULL,
  password VARCHAR2(100) NOT NULL,
  role     VARCHAR2(20)  NOT NULL,
  enabled  CHAR(1)       DEFAULT 'S' NOT NULL,
  CONSTRAINT uk_usuario_username UNIQUE (username),
  CONSTRAINT ck_usuario_enabled CHECK (enabled IN ('S','N'))
);

